-- GymTrack Exercise Library
-- Run this second in Supabase SQL Editor

INSERT INTO exercises (name, muscle_group, equipment) VALUES
  ('Incline Barbell Press',     'Chest',      'Barbell'),
  ('Flat Barbell Press',        'Chest',      'Barbell'),
  ('Incline Dumbbell Press',    'Chest',      'Dumbbell'),
  ('Cable Chest Fly',           'Chest',      'Cable'),
  ('Dip',                       'Chest',      'Bodyweight'),
  ('Pull-Up',                   'Back',       'Bodyweight'),
  ('Barbell Row',               'Back',       'Barbell'),
  ('Cable Row',                 'Back',       'Cable'),
  ('Lat Pulldown',              'Back',       'Cable'),
  ('Face Pull',                 'Rear Delt',  'Cable'),
  ('Barbell Curl',              'Biceps',     'Barbell'),
  ('Incline Dumbbell Curl',     'Biceps',     'Dumbbell'),
  ('Hammer Curl',               'Biceps',     'Dumbbell'),
  ('Skull Crusher',             'Triceps',    'Barbell'),
  ('Tricep Pushdown',           'Triceps',    'Cable'),
  ('OHP Barbell',               'Shoulders',  'Barbell'),
  ('Lateral Raise',             'Shoulders',  'Dumbbell'),
  ('Rear Delt Fly',             'Rear Delt',  'Dumbbell'),
  ('Squat',                     'Legs',       'Barbell'),
  ('Romanian Deadlift',         'Legs',       'Barbell'),
  ('Leg Press',                 'Legs',       'Machine'),
  ('Leg Curl',                  'Hamstrings', 'Machine'),
  ('Leg Extension',             'Quads',      'Machine'),
  ('Hip Thrust',                'Glutes',     'Barbell'),
  ('Calf Raise',                'Calves',     'Machine'),
  ('Hanging Leg Raise',         'Core',       'Bodyweight'),
  ('Cable Crunch',              'Core',       'Cable'),
  ('Deadlift',                  'Back',       'Barbell'),
  ('T-Bar Row',                 'Back',       'Barbell'),
  ('Chest Supported Row',       'Back',       'Dumbbell'),
  ('Preacher Curl',             'Biceps',     'Barbell'),
  ('Cable Lateral Raise',       'Shoulders',  'Cable'),
  ('Arnold Press',              'Shoulders',  'Dumbbell'),
  ('Reverse Curl',              'Biceps',     'Barbell'),
  ('Close Grip Bench',          'Triceps',    'Barbell'),
  ('Overhead Tricep Extension', 'Triceps',    'Dumbbell'),
  ('Bulgarian Split Squat',     'Legs',       'Dumbbell'),
  ('Walking Lunge',             'Legs',       'Dumbbell'),
  ('Glute Bridge',              'Glutes',     'Bodyweight'),
  ('Ab Wheel Rollout',          'Core',       'Equipment'),
  ('Plank',                     'Core',       'Bodyweight'),
  ('Russian Twist',             'Core',       'Bodyweight'),
  ('Seated Calf Raise',         'Calves',     'Machine'),
  ('Pec Deck',                  'Chest',      'Machine'),
  ('Hack Squat',                'Legs',       'Machine')
ON CONFLICT (name) DO NOTHING;
